// single-spa-angular-app/src/app/app.component.ts
import { Component, OnInit, OnDestroy } from '@angular/core';
import { Subscription } from 'rxjs';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.scss']
})
export class AppComponent implements OnInit, OnDestroy {
  title = 'single-spa-angular-app';
  count = 0;
  mountedAt = new Date().toLocaleString();
  userState: any;
  employees: any[] = [];
  events: any[] = [];
  private userStateSub: Subscription;
  private employeesSub: Subscription;
  private eventsSub: Subscription;
  features = [
    'TypeScript Integration',
    'Dependency Injection',
    'Angular Router',
    'Component Architecture',
    'RxJS Observables'
  ];

  get doubleCount(): number {
    return this.count * 2;
  }

  get employeePreview(): string {
    if (this.employees.length === 0) return '';
    const preview = this.employees.slice(0, 3).map(emp => emp.name).join(', ');
    return this.employees.length > 3 ? `${preview} (+${this.employees.length - 3} more)` : preview;
  }

  get recentEvents(): any[] {
    return this.events.slice(-3);
  }

  increment(): void {
    this.count++;
    if ((window as any).stateManager) {
      (window as any).stateManager.emit('angular-counter', { count: this.count, app: 'Angular' });
    }
  }

  reset(): void {
    this.count = 0;
  }

  ngOnInit(): void {
    if ((window as any).stateManager) {
      this.userStateSub = (window as any).stateManager.userState$.subscribe(
        (state: any) => this.userState = state
      );
      this.employeesSub = (window as any).stateManager.employees$.subscribe(
        (employees: any[]) => this.employees = employees
      );
      this.eventsSub = (window as any).stateManager.events$.subscribe(
        (event: any) => {
          console.log('🅰️ Angular received event:', event);
          this.events = [...this.events.slice(-4), event]; // Keep last 5 events
        }
      );
    }
  }

  loadEmployees(): void {
    if ((window as any).stateManager) {
      (window as any).stateManager.loadEmployees();
    }
  }

  broadcastMessage(): void {
    if ((window as any).stateManager) {
      const event = {
        type: 'user-interaction',
        source: 'Angular',
        timestamp: new Date().toISOString(),
        data: { message: 'Hello from Angular!' }
      };
      (window as any).stateManager.emit('cross-app-message', event);
    }
  }

  clearEmployees(): void {
    if ((window as any).stateManager) {
      (window as any).stateManager.employees$.next([]);
    }
  }

  ngOnDestroy(): void {
    if (this.userStateSub) {
      this.userStateSub.unsubscribe();
    }
    if (this.employeesSub) {
      this.employeesSub.unsubscribe();
    }
    if (this.eventsSub) {
      this.eventsSub.unsubscribe();
    }
  }
}

<div style="padding: 20px; border: 2px solid #dd0031; border-radius: 8px; margin: 10px 0; background: #f8f9fa; font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;">
  <h2 style="color: #dd0031; margin: 0 0 15px 0;">
    <img src="https://angular.io/assets/images/logos/angular/angular.png" width="40" height="40" style="vertical-align: middle; margin-right: 10px;">
    Angular Microfrontend
  </h2>
  <p><strong>Framework:</strong> Angular 8 with TypeScript</p>
  <p><strong>Features:</strong> Component architecture, dependency injection, routing</p>
  <p><strong>Mounted at:</strong> {{ mountedAt }}</p>
  
  <div style="margin: 15px 0; padding: 15px; background: white; border-radius: 6px;">
    <h4 style="color: #495057; margin: 0 0 10px 0;">Interactive Counter</h4>
    <button 
      (click)="increment()"
      style="background: #dd0031; color: white; border: none; padding: 8px 16px; border-radius: 4px; cursor: pointer; margin-right: 10px;"
    >
      Count: {{ count }}
    </button>
    <button 
      (click)="reset()"
      style="background: #6c757d; color: white; border: none; padding: 8px 16px; border-radius: 4px; cursor: pointer;"
    >
      Reset
    </button>
    <p style="margin: 10px 0 0 0; font-size: 0.9em; color: #6c757d;">Double: {{ doubleCount }}</p>
  </div>
  
  <div style="margin: 15px 0; padding: 15px; background: white; border-radius: 6px;">
    <h4 style="color: #495057; margin: 0 0 10px 0;">Navigation</h4>
    <nav style="margin-bottom: 15px;">
      <a 
        routerLink="/angular" 
        routerLinkActive="active" 
        [routerLinkActiveOptions]="{exact: true}"
        style="margin-right: 15px; color: #dd0031; text-decoration: none; padding: 5px 10px; border-radius: 4px;"
      >
        List
      </a>
      <a 
        routerLink="/angular/detail" 
        routerLinkActive="active" 
        [routerLinkActiveOptions]="{exact: true}"
        style="color: #dd0031; text-decoration: none; padding: 5px 10px; border-radius: 4px;"
      >
        Detail
      </a>
    </nav>
    <router-outlet></router-outlet>
  </div>
  
  <!-- Shared State Showcase -->
  <div style="margin: 15px 0; padding: 15px; background: linear-gradient(135deg, #667eea 0%, #764ba2 100%); border-radius: 8px; color: white;">
    <h4 style="margin: 0 0 15px 0; color: white;">🔄 Shared State Management (Angular)</h4>
    
    <div style="background: rgba(255,255,255,0.1); padding: 10px; border-radius: 6px; margin-bottom: 10px;">
      <strong>👤 User State:</strong><br>
      <span *ngIf="userState; else notLoggedIn">
        ✅ Logged in as: <strong>{{ userState.user?.username || 'Unknown' }}</strong>
      </span>
      <ng-template #notLoggedIn>❌ Not logged in</ng-template>
    </div>
    
    <div style="background: rgba(255,255,255,0.1); padding: 10px; border-radius: 6px; margin-bottom: 10px;">
      <strong>👥 Employee Data:</strong><br>
      📊 Count: <strong>{{ employees.length }}</strong><br>
      👀 Preview: 
      <span *ngIf="employees.length > 0; else noEmployees">
        {{ employeePreview }}
      </span>
      <ng-template #noEmployees>No employees loaded</ng-template>
    </div>
    
    <div style="display: flex; gap: 10px; flex-wrap: wrap; margin-bottom: 10px;">
      <button 
        (click)="loadEmployees()"
        style="background: #28a745; color: white; border: none; padding: 8px 12px; border-radius: 4px; cursor: pointer; font-size: 12px;"
      >
        👥 Load Employees
      </button>
      <button 
        (click)="broadcastMessage()"
        style="background: #007bff; color: white; border: none; padding: 8px 12px; border-radius: 4px; cursor: pointer; font-size: 12px;"
      >
        📡 Broadcast from Angular
      </button>
      <button 
        (click)="clearEmployees()"
        style="background: #dc3545; color: white; border: none; padding: 8px 12px; border-radius: 4px; cursor: pointer; font-size: 12px;"
      >
        🗑️ Clear Data
      </button>
    </div>
    
    <div *ngIf="events.length > 0" style="background: rgba(255,255,255,0.1); padding: 10px; border-radius: 6px; font-size: 12px;">
      <strong>📨 Recent Events:</strong><br>
      <div *ngFor="let event of recentEvents" style="margin-top: 5px;">
        {{ event.source }}: {{ event.data?.message || event.type }}
      </div>
    </div>
  </div>
  
  <div style="margin-top: 15px; font-size: 0.9em; color: #6c757d;">
    <strong>Angular Features:</strong>
    <ul style="margin: 5px 0; padding-left: 20px;">
      <li *ngFor="let feature of features">{{ feature }}</li>
    </ul>
  </div>
</div>

// single-spa-vue-app/src/App.vue
<template>
  <div class="vue-app-container">
    <h2 style="color: #4fc08d; margin: 0 0 15px 0;">
      <img src="https://vuejs.org/images/logo.png" width="40" height="40" style="vertical-align: middle; margin-right: 10px;">
      Vue.js Microfrontend
    </h2>
    <p><strong>Framework:</strong> Vue.js 2 with Vue Router</p>
    <p><strong>Features:</strong> Reactive data binding, component system, routing</p>
    <p><strong>Mounted at:</strong> {{ mountedAt }}</p>

    <div class="counter-section">
      <h4>Reactive Counter</h4>
      <button class="btn-primary" @click="increment">
        Count: {{ count }}
      </button>
      <button class="btn-secondary" @click="reset">
        Reset
      </button>
      <button class="btn-success" @click="loadEmployees">
        Load Employees
      </button>
      <p class="counter-info">Double: {{ doubleCount }}</p>
    </div>

    <div class="navigation-section">
      <h4>Navigation</h4>
      <nav class="nav-links">
        <router-link to="/" class="nav-link" active-class="active-link">
          List
        </router-link>
        <router-link to="/detail" class="nav-link" active-class="active-link">
          Detail
        </router-link>
      </nav>
      <router-view></router-view>
    </div>

    <!-- Shared State Showcase -->
    <div class="shared-state-showcase">
      <h4>🔄 Shared State Management (Vue)</h4>
      
      <div class="state-info">
        <strong>👤 User State:</strong><br>
        <span v-if="userState">
          ✅ Logged in as: <strong>{{ userState.user?.username || 'Unknown' }}</strong>
        </span>
        <span v-else>❌ Not logged in</span>
      </div>
      
      <div class="state-info">
        <strong>👥 Employee Data:</strong><br>
        📊 Count: <strong>{{ employees.length }}</strong><br>
        👀 Preview: 
        <span v-if="employees.length > 0">
          {{ employees.slice(0, 3).map(emp => emp.name).join(', ') }}
          <span v-if="employees.length > 3">(+{{ employees.length - 3 }} more)</span>
        </span>
        <span v-else>No employees loaded</span>
      </div>
      
      <div class="showcase-buttons">
        <button class="btn-employees" @click="loadEmployees">
          👥 Load Employees
        </button>
        <button class="btn-broadcast" @click="broadcastMessage">
          📡 Broadcast from Vue
        </button>
        <button class="btn-clear" @click="clearEmployees">
          🗑️ Clear Data
        </button>
      </div>
      
      <div v-if="events.length > 0" class="events-info">
        <strong>📨 Recent Events:</strong><br>
        <div v-for="(event, i) in events.slice(-3)" :key="i" class="event-item">
          {{ event.source }}: {{ event.data?.message || event.type }}
        </div>
      </div>
    </div>

    <div class="features-section">
      <strong>Vue.js Features:</strong>
      <ul>
        <li v-for="feature in features" :key="feature">{{ feature }}</li>
      </ul>
    </div>
  </div>
</template>

<script>
export default {
  name: 'app',
  data() {
    return {
      count: 0,
      mountedAt: new Date().toLocaleString(),
      userState: null,
      employees: [],
      events: [],
      features: [
        'Reactive Data Binding',
        'Component-based Architecture',
        'Vue Router Integration',
        'Template Syntax',
        'Computed Properties',
      ],
    };
  },
  computed: {
    doubleCount() {
      return this.count * 2;
    },
  },
  mounted() {
    if (window.stateManager) {
      this.userStateSub = window.stateManager.userState$.subscribe((state) => {
        this.userState = state;
      });
      this.employeesSub = window.stateManager.employees$.subscribe((employees) => {
        this.employees = employees;
      });
      this.eventsSub = window.stateManager.events$.subscribe((event) => {
        // eslint-disable-next-line no-console
        console.log('💚 Vue received event:', event);
        this.events = [...this.events.slice(-4), event]; // Keep last 5 events
      });
    }
  },
  beforeDestroy() {
    if (this.userStateSub) {
      this.userStateSub.unsubscribe();
    }
    if (this.employeesSub) {
      this.employeesSub.unsubscribe();
    }
    if (this.eventsSub) {
      this.eventsSub.unsubscribe();
    }
  },
  methods: {
    increment() {
      this.count += 1;
      if (window.stateManager) {
        window.stateManager.emit('vue-counter', { count: this.count, app: 'Vue' });
      }
    },
    reset() {
      this.count = 0;
    },
    loadEmployees() {
      if (window.stateManager) {
        window.stateManager.loadEmployees();
      }
    },
    broadcastMessage() {
      if (window.stateManager) {
        const event = {
          type: 'user-interaction',
          source: 'Vue',
          timestamp: new Date().toISOString(),
          data: { message: 'Hello from Vue!' }
        };
        window.stateManager.emit('cross-app-message', event);
      }
    },
    clearEmployees() {
      if (window.stateManager) {
        window.stateManager.employees$.next([]);
      }
    },
  },
  components: {},
};
</script>

<style lang="scss" scoped>
.vue-app-container {
  padding: 20px;
  border: 2px solid #4fc08d;
  border-radius: 8px;
  margin: 10px 0;
  background: #f8f9fa;
  font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
}

.counter-section, .navigation-section {
  margin: 15px 0;
  padding: 15px;
  background: white;
  border-radius: 6px;

  h4 {
    color: #495057;
    margin: 0 0 10px 0;
  }
}

.btn-primary {
  background: #4fc08d;
  color: white;
  border: none;
  padding: 8px 16px;
  border-radius: 4px;
  cursor: pointer;
  margin-right: 10px;
}

.btn-secondary {
  background: #6c757d;
  color: white;
  border: none;
  padding: 8px 16px;
  border-radius: 4px;
  cursor: pointer;
}

.btn-success {
  background: #28a745;
  color: white;
  border: none;
  padding: 8px 16px;
  border-radius: 4px;
  cursor: pointer;
  margin-left: 10px;
}

.counter-info {
  margin: 10px 0 0 0;
  font-size: 0.9em;
  color: #6c757d;
}

.nav-links {
  margin-bottom: 15px;
}

.nav-link {
  margin-right: 15px;
  color: #4fc08d;
  text-decoration: none;
  padding: 5px 10px;
  border-radius: 4px;
}

.active-link {
  background-color: #4fc08d !important;
  color: white !important;
}

.shared-state-showcase {
  margin: 15px 0;
  padding: 15px;
  background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
  border-radius: 8px;
  color: white;

  h4 {
    margin: 0 0 15px 0;
    color: white;
  }

  .state-info {
    background: rgba(255,255,255,0.1);
    padding: 10px;
    border-radius: 6px;
    margin-bottom: 10px;
  }

  .showcase-buttons {
    display: flex;
    gap: 10px;
    flex-wrap: wrap;
    margin-bottom: 10px;
  }

  .btn-employees {
    background: #28a745;
    color: white;
    border: none;
    padding: 8px 12px;
    border-radius: 4px;
    cursor: pointer;
    font-size: 12px;
  }

  .btn-broadcast {
    background: #007bff;
    color: white;
    border: none;
    padding: 8px 12px;
    border-radius: 4px;
    cursor: pointer;
    font-size: 12px;
  }

  .btn-clear {
    background: #dc3545;
    color: white;
    border: none;
    padding: 8px 12px;
    border-radius: 4px;
    cursor: pointer;
    font-size: 12px;
  }

  .events-info {
    background: rgba(255,255,255,0.1);
    padding: 10px;
    border-radius: 6px;
    font-size: 12px;

    .event-item {
      margin-top: 5px;
    }
  }
}

.features-section {
  margin-top: 15px;
  font-size: 0.9em;
  color: #6c757d;

  ul {
    margin: 5px 0;
    padding-left: 20px;
  }
}
</style>
