// single-spa-react-app/src/App.js
import React, { useState, useEffect } from 'react';
import './App.scss';
import { useSharedStateShowcase } from '../../../shared/shared-state-showcase.js';

// Custom hook for global state
function useGlobalState() {
  const [userState, setUserState] = useState(null);
  
  useEffect(() => {
    if (window.stateManager) {
      const userSub = window.stateManager.userState$.subscribe(setUserState);
      const eventsSub = window.stateManager.events$.subscribe(event => {
        console.log('⚛️ React received event:', event);
      });
      return () => {
        userSub.unsubscribe();
        eventsSub.unsubscribe();
      };
    }
  }, []);
  
  return userState;
}

import {
  Route,
  NavLink,
  Switch,
} from 'react-router-dom';

import List from './components/List';
import Detail from './components/Detail';

function App() {
  const [count, setCount] = React.useState(0);
  const [mounted] = React.useState(new Date().toLocaleString());
  const userState = useGlobalState();
  const { userState: sharedUserState, employees, events } = useSharedStateShowcase() || {};
  
  const features = [
    'Hooks and Functional Components',
    'React Router for Navigation',
    'Component State Management',
    'Virtual DOM Rendering',
    'JSX Syntax'
  ];

  return (
    <div style={{
      padding: '20px',
      border: '2px solid #61dafb',
      borderRadius: '8px',
      margin: '10px 0',
      background: '#f8f9fa',
      fontFamily: '-apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif'
    }}>
      <h2 style={{ color: '#61dafb', margin: '0 0 15px 0' }}>
        <img 
          src="data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9Ii0xMS41IC0xMC4yMzE3NCAyMyAyMC40NjM0OCI+CiAgPHRpdGxlPlJlYWN0IExvZ288L3RpdGxlPgogIDxjaXJjbGUgY3g9IjAiIGN5PSIwIiByPSIyLjA1IiBmaWxsPSIjNjFkYWZiIi8+CiAgPGcgc3Ryb2tlPSIjNjFkYWZiIiBzdHJva2Utd2lkdGg9IjEiIGZpbGw9Im5vbmUiPgogICAgPGVsbGlwc2Ugcng9IjExIiByeT0iNC4yIi8+CiAgICA8ZWxsaXBzZSByeD0iMTEiIHJ5PSI0LjIiIHRyYW5zZm9ybT0icm90YXRlKDYwKSIvPgogICAgPGVsbGlwc2Ugcng9IjExIiByeT0iNC4yIiB0cmFuc2Zvcm09InJvdGF0ZSgxMjApIi8+CiAgPC9nPgo8L3N2Zz4K" 
          width="40" 
          height="40" 
          style={{ verticalAlign: 'middle', marginRight: '10px' }}
          alt="React logo"
        />
        React Microfrontend
      </h2>
      <p><strong>Framework:</strong> React 16 with Hooks</p>
      <p><strong>Features:</strong> Modern React patterns, routing, state management</p>
      <p><strong>Mounted at:</strong> {mounted}</p>
      
      <div style={{
        margin: '15px 0',
        padding: '15px',
        background: 'white',
        borderRadius: '6px'
      }}>
        <h4 style={{ color: '#495057', margin: '0 0 10px 0' }}>Interactive Counter</h4>
        <button 
          onClick={() => {
            setCount(count + 1);
            if (window.stateManager) {
              window.stateManager.emit('react-counter', { count: count + 1, app: 'React' });
            }
          }}
          style={{
            background: '#61dafb',
            color: 'white',
            border: 'none',
            padding: '8px 16px',
            borderRadius: '4px',
            cursor: 'pointer',
            marginRight: '10px'
          }}
        >
          Count: {count}
        </button>
        <button 
          onClick={() => {
            if (window.stateManager) {
              window.stateManager.loadEmployees();
            }
          }}
          style={{
            background: '#28a745',
            color: 'white',
            border: 'none',
            padding: '8px 16px',
            borderRadius: '4px',
            cursor: 'pointer'
          }}
        >
          Load Employees
        </button>
        <button 
          onClick={() => setCount(0)}
          style={{
            background: '#6c757d',
            color: 'white',
            border: 'none',
            padding: '8px 16px',
            borderRadius: '4px',
            cursor: 'pointer'
          }}
        >
          Reset
        </button>
      </div>
      
      <div style={{
        margin: '15px 0',
        padding: '15px',
        background: 'white',
        borderRadius: '6px'
      }}>
        <h4 style={{ color: '#495057', margin: '0 0 10px 0' }}>Navigation</h4>
        <nav style={{ marginBottom: '15px' }}>
          <NavLink 
            to="/" 
            activeClassName="active" 
            exact={true}
            style={{
              marginRight: '15px',
              color: '#61dafb',
              textDecoration: 'none'
            }}
          >
            List
          </NavLink>
          <NavLink 
            to="/detail" 
            activeClassName="active" 
            exact={true}
            style={{
              color: '#61dafb',
              textDecoration: 'none'
            }}
          >
            Detail
          </NavLink>
        </nav>
        <Switch>
          <Route exact path="/" component={List} />
          <Route path="/detail" component={Detail} />
        </Switch>
      </div>
      
      {/* Shared State Showcase */}
      <div style={{
        margin: '15px 0',
        padding: '15px',
        background: 'linear-gradient(135deg, #667eea 0%, #764ba2 100%)',
        borderRadius: '8px',
        color: 'white'
      }}>
        <h4 style={{ margin: '0 0 15px 0', color: 'white' }}>🔄 Shared State Management (React)</h4>
        
        <div style={{
          background: 'rgba(255,255,255,0.1)',
          padding: '10px',
          borderRadius: '6px',
          marginBottom: '10px'
        }}>
          <strong>👤 User State:</strong><br/>
          {sharedUserState ? 
            `✅ Logged in as: ${sharedUserState.user?.username || 'Unknown'}` :
            '❌ Not logged in'
          }
        </div>
        
        <div style={{
          background: 'rgba(255,255,255,0.1)',
          padding: '10px',
          borderRadius: '6px',
          marginBottom: '10px'
        }}>
          <strong>👥 Employee Data:</strong><br/>
          📊 Count: <strong>{employees?.length || 0}</strong><br/>
          👀 Preview: {employees && employees.length > 0 ? 
            employees.slice(0, 3).map(emp => emp.name).join(', ') + 
            (employees.length > 3 ? ` (+${employees.length - 3} more)` : '') : 
            'No employees loaded'
          }
        </div>
        
        <div style={{ display: 'flex', gap: '10px', flexWrap: 'wrap' }}>
          <button 
            onClick={() => window.stateManager?.loadEmployees()}
            style={{
              background: '#28a745',
              color: 'white',
              border: 'none',
              padding: '8px 12px',
              borderRadius: '4px',
              cursor: 'pointer',
              fontSize: '12px'
            }}
          >
            👥 Load Employees
          </button>
          <button 
            onClick={() => {
              if (window.stateManager) {
                const event = {
                  type: 'user-interaction',
                  source: 'React',
                  timestamp: new Date().toISOString(),
                  data: { message: 'Hello from React!' }
                };
                window.stateManager.emit('cross-app-message', event);
              }
            }}
            style={{
              background: '#007bff',
              color: 'white',
              border: 'none',
              padding: '8px 12px',
              borderRadius: '4px',
              cursor: 'pointer',
              fontSize: '12px'
            }}
          >
            📡 Broadcast from React
          </button>
          <button 
            onClick={() => window.stateManager?.employees$.next([])}
            style={{
              background: '#dc3545',
              color: 'white',
              border: 'none',
              padding: '8px 12px',
              borderRadius: '4px',
              cursor: 'pointer',
              fontSize: '12px'
            }}
          >
            🗑️ Clear Data
          </button>
        </div>
        
        {events && events.length > 0 && (
          <div style={{
            background: 'rgba(255,255,255,0.1)',
            padding: '10px',
            borderRadius: '6px',
            marginTop: '10px',
            fontSize: '12px'
          }}>
            <strong>📨 Recent Events:</strong><br/>
            {events.slice(-3).map((event, i) => (
              <div key={i} style={{ marginTop: '5px' }}>
                {event.source}: {event.data?.message || event.type}
              </div>
            ))}
          </div>
        )}
      </div>
      
      <div style={{ marginTop: '15px', fontSize: '0.9em', color: '#6c757d' }}>
        <strong>React Features:</strong>
        <ul style={{ margin: '5px 0', paddingLeft: '20px' }}>
          {features.map((feature, index) => (
            <li key={index}>{feature}</li>
          ))}
        </ul>
      </div>
    </div>
  );
}

export default App;

// single-spa-vue-app/src/App.vue
<template>
  <div class="vue-app-container">
    <h2 style="color: #4fc08d; margin: 0 0 15px 0;">
      <img src="https://vuejs.org/images/logo.png" width="40" height="40" style="vertical-align: middle; margin-right: 10px;">
      Vue.js Microfrontend
    </h2>
    <p><strong>Framework:</strong> Vue.js 2 with Vue Router</p>
    <p><strong>Features:</strong> Reactive data binding, component system, routing</p>
    <p><strong>Mounted at:</strong> {{ mountedAt }}</p>

    <div class="counter-section">
      <h4>Reactive Counter</h4>
      <button class="btn-primary" @click="increment">
        Count: {{ count }}
      </button>
      <button class="btn-secondary" @click="reset">
        Reset
      </button>
      <button class="btn-success" @click="loadEmployees">
        Load Employees
      </button>
      <p class="counter-info">Double: {{ doubleCount }}</p>
    </div>

    <div class="navigation-section">
      <h4>Navigation</h4>
      <nav class="nav-links">
        <router-link to="/" class="nav-link" active-class="active-link">
          List
        </router-link>
        <router-link to="/detail" class="nav-link" active-class="active-link">
          Detail
        </router-link>
      </nav>
      <router-view></router-view>
    </div>

    <!-- Shared State Showcase -->
    <div class="shared-state-showcase">
      <h4>🔄 Shared State Management (Vue)</h4>
      
      <div class="state-info">
        <strong>👤 User State:</strong><br>
        <span v-if="userState">
          ✅ Logged in as: <strong>{{ userState.user?.username || 'Unknown' }}</strong>
        </span>
        <span v-else>❌ Not logged in</span>
      </div>
      
      <div class="state-info">
        <strong>👥 Employee Data:</strong><br>
        📊 Count: <strong>{{ employees.length }}</strong><br>
        👀 Preview: 
        <span v-if="employees.length > 0">
          {{ employees.slice(0, 3).map(emp => emp.name).join(', ') }}
          <span v-if="employees.length > 3">(+{{ employees.length - 3 }} more)</span>
        </span>
        <span v-else>No employees loaded</span>
      </div>
      
      <div class="showcase-buttons">
        <button class="btn-employees" @click="loadEmployees">
          👥 Load Employees
        </button>
        <button class="btn-broadcast" @click="broadcastMessage">
          📡 Broadcast from Vue
        </button>
        <button class="btn-clear" @click="clearEmployees">
          🗑️ Clear Data
        </button>
      </div>
      
      <div v-if="events.length > 0" class="events-info">
        <strong>📨 Recent Events:</strong><br>
        <div v-for="(event, i) in events.slice(-3)" :key="i" class="event-item">
          {{ event.source }}: {{ event.data?.message || event.type }}
        </div>
      </div>
    </div>

    <div class="features-section">
      <strong>Vue.js Features:</strong>
      <ul>
        <li v-for="feature in features" :key="feature">{{ feature }}</li>
      </ul>
    </div>
  </div>
</template>

<script>
export default {
  name: 'app',
  data() {
    return {
      count: 0,
      mountedAt: new Date().toLocaleString(),
      userState: null,
      employees: [],
      events: [],
      features: [
        'Reactive Data Binding',
        'Component-based Architecture',
        'Vue Router Integration',
        'Template Syntax',
        'Computed Properties',
      ],
    };
  },
  computed: {
    doubleCount() {
      return this.count * 2;
    },
  },
  mounted() {
    if (window.stateManager) {
      this.userStateSub = window.stateManager.userState$.subscribe((state) => {
        this.userState = state;
      });
      this.employeesSub = window.stateManager.employees$.subscribe((employees) => {
        this.employees = employees;
      });
      this.eventsSub = window.stateManager.events$.subscribe((event) => {
        // eslint-disable-next-line no-console
        console.log('💚 Vue received event:', event);
        this.events = [...this.events.slice(-4), event]; // Keep last 5 events
      });
    }
  },
  beforeDestroy() {
    if (this.userStateSub) {
      this.userStateSub.unsubscribe();
    }
    if (this.employeesSub) {
      this.employeesSub.unsubscribe();
    }
    if (this.eventsSub) {
      this.eventsSub.unsubscribe();
    }
  },
  methods: {
    increment() {
      this.count += 1;
      if (window.stateManager) {
        window.stateManager.emit('vue-counter', { count: this.count, app: 'Vue' });
      }
    },
    reset() {
      this.count = 0;
    },
    loadEmployees() {
      if (window.stateManager) {
        window.stateManager.loadEmployees();
      }
    },
    broadcastMessage() {
      if (window.stateManager) {
        const event = {
          type: 'user-interaction',
          source: 'Vue',
          timestamp: new Date().toISOString(),
          data: { message: 'Hello from Vue!' }
        };
        window.stateManager.emit('cross-app-message', event);
      }
    },
    clearEmployees() {
      if (window.stateManager) {
        window.stateManager.employees$.next([]);
      }
    },
  },
  components: {},
};
</script>

<style lang="scss" scoped>
.vue-app-container {
  padding: 20px;
  border: 2px solid #4fc08d;
  border-radius: 8px;
  margin: 10px 0;
  background: #f8f9fa;
  font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
}

.counter-section, .navigation-section {
  margin: 15px 0;
  padding: 15px;
  background: white;
  border-radius: 6px;

  h4 {
    color: #495057;
    margin: 0 0 10px 0;
  }
}

.btn-primary {
  background: #4fc08d;
  color: white;
  border: none;
  padding: 8px 16px;
  border-radius: 4px;
  cursor: pointer;
  margin-right: 10px;
}

.btn-secondary {
  background: #6c757d;
  color: white;
  border: none;
  padding: 8px 16px;
  border-radius: 4px;
  cursor: pointer;
}

.btn-success {
  background: #28a745;
  color: white;
  border: none;
  padding: 8px 16px;
  border-radius: 4px;
  cursor: pointer;
  margin-left: 10px;
}

.counter-info {
  margin: 10px 0 0 0;
  font-size: 0.9em;
  color: #6c757d;
}

.nav-links {
  margin-bottom: 15px;
}

.nav-link {
  margin-right: 15px;
  color: #4fc08d;
  text-decoration: none;
  padding: 5px 10px;
  border-radius: 4px;
}

.active-link {
  background-color: #4fc08d !important;
  color: white !important;
}

.shared-state-showcase {
  margin: 15px 0;
  padding: 15px;
  background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
  border-radius: 8px;
  color: white;

  h4 {
    margin: 0 0 15px 0;
    color: white;
  }

  .state-info {
    background: rgba(255,255,255,0.1);
    padding: 10px;
    border-radius: 6px;
    margin-bottom: 10px;
  }

  .showcase-buttons {
    display: flex;
    gap: 10px;
    flex-wrap: wrap;
    margin-bottom: 10px;
  }

  .btn-employees {
    background: #28a745;
    color: white;
    border: none;
    padding: 8px 12px;
    border-radius: 4px;
    cursor: pointer;
    font-size: 12px;
  }

  .btn-broadcast {
    background: #007bff;
    color: white;
    border: none;
    padding: 8px 12px;
    border-radius: 4px;
    cursor: pointer;
    font-size: 12px;
  }

  .btn-clear {
    background: #dc3545;
    color: white;
    border: none;
    padding: 8px 12px;
    border-radius: 4px;
    cursor: pointer;
    font-size: 12px;
  }

  .events-info {
    background: rgba(255,255,255,0.1);
    padding: 10px;
    border-radius: 6px;
    font-size: 12px;

    .event-item {
      margin-top: 5px;
    }
  }
}

.features-section {
  margin-top: 15px;
  font-size: 0.9em;
  color: #6c757d;

  ul {
    margin: 5px 0;
    padding-left: 20px;
  }
}
</style>
